### ISSUE TITLE
Example vignette import error

### ISSUE THREAD

**Issue by mariumtapal** [smith-tinkerlab/repytah#322]
Hello @Chenhui-Jia, @thuntran, @bwang64, @zoiezhao! One of the testers of the package found a bug in our code. In the example vignette, the import statement gives errors:
```# Import csv
file_in = pd.read_csv(os.path.join(os.path.dirname('__file__'), "../input. 􏰀→csv")).to_numpy()
fv_mat = file_in

FileNotFoundError: [Errno 2] No such file or directory: '../input.csv'
```

Testing this myself in a separate environment, I also get this error.

I've tried playing around with the paths but didn't have luck fixing it. I also looked at and tried some solutions in [this](https://stackoverflow.com/questions/779495/access-data-in-package-subdirectory/5601839#5601839) article. Does anyone have ideas?

**Comment by thuntran** [comment]
Which IDE did you use? I just pulled the changes and ran tests on PyCharm and I think everything passed for me.

When I ran the tests in the terminal, it didn't give me the error that you encountered, but something else instead:

`self = <test_utilities.TestUtilities testMethod=test_get_y_labels>

    def test_get_y_labels(self):
        """
        Tests if get_y_labels generates the correct labels for a visualization
        with width_vec and anno_vec.
        """

        width_vec = np.array([[1], [1], [3], [4], [4], [5], [5], [6], [6]])
        anno_vec = np.array([1, 2, 1, 1, 2, 1, 1, 1, 2])
        expect_output = np.array(['0', 'w = 1, a = 1', 'w = 1, a = 2',
                                  'w = 3, a = 1', 'w = 4, a = 1',
                                  'w = 4, a = 2', 'w = 5, a = 1',
                                  'w = 5, a = 1', 'w = 6, a = 1',
                                  'w = 6, a = 2'])

>       output = get_y_labels(width_vec, anno_vec)
E       NameError: name 'get_y_labels' is not defined`

I think the directory still works well for me. This is kinda strange...

**Comment by mariumtapal** [comment]
@thuntran i tried in VScode and the terminal but in a different conda environment. Perhaps could you try in a different directory and conda environment?

**Comment by thuntran** [comment]
@mariumtapal So I tried running tests in a different conda env and directory, and I got the same error as I mentioned above plus another FileNotFound error but it's on another file:

` FileNotFoundError: [Errno 2] No such file or directory: 'test/hierarchical_out_file.mat'`
